# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bmahe/Epitech/tek2/projet/B-YEP-400-BDX-4-1-indiestudio-remi.huguet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bmahe/Epitech/tek2/projet/B-YEP-400-BDX-4-1-indiestudio-remi.huguet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bmahe/Epitech/tek2/projet/B-YEP-400-BDX-4-1-indiestudio-remi.huguet/CMakeFiles /home/bmahe/Epitech/tek2/projet/B-YEP-400-BDX-4-1-indiestudio-remi.huguet/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bmahe/Epitech/tek2/projet/B-YEP-400-BDX-4-1-indiestudio-remi.huguet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

GameEngine/Event/window_closed.o: GameEngine/Event/window_closed.cpp.o

.PHONY : GameEngine/Event/window_closed.o

# target to build an object file
GameEngine/Event/window_closed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Event/window_closed.cpp.o
.PHONY : GameEngine/Event/window_closed.cpp.o

GameEngine/Event/window_closed.i: GameEngine/Event/window_closed.cpp.i

.PHONY : GameEngine/Event/window_closed.i

# target to preprocess a source file
GameEngine/Event/window_closed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Event/window_closed.cpp.i
.PHONY : GameEngine/Event/window_closed.cpp.i

GameEngine/Event/window_closed.s: GameEngine/Event/window_closed.cpp.s

.PHONY : GameEngine/Event/window_closed.s

# target to generate assembly for a file
GameEngine/Event/window_closed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Event/window_closed.cpp.s
.PHONY : GameEngine/Event/window_closed.cpp.s

GameEngine/Keyboard/key_pressed.o: GameEngine/Keyboard/key_pressed.cpp.o

.PHONY : GameEngine/Keyboard/key_pressed.o

# target to build an object file
GameEngine/Keyboard/key_pressed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Keyboard/key_pressed.cpp.o
.PHONY : GameEngine/Keyboard/key_pressed.cpp.o

GameEngine/Keyboard/key_pressed.i: GameEngine/Keyboard/key_pressed.cpp.i

.PHONY : GameEngine/Keyboard/key_pressed.i

# target to preprocess a source file
GameEngine/Keyboard/key_pressed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Keyboard/key_pressed.cpp.i
.PHONY : GameEngine/Keyboard/key_pressed.cpp.i

GameEngine/Keyboard/key_pressed.s: GameEngine/Keyboard/key_pressed.cpp.s

.PHONY : GameEngine/Keyboard/key_pressed.s

# target to generate assembly for a file
GameEngine/Keyboard/key_pressed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Keyboard/key_pressed.cpp.s
.PHONY : GameEngine/Keyboard/key_pressed.cpp.s

GameEngine/MakeSound/MakeSound.o: GameEngine/MakeSound/MakeSound.cpp.o

.PHONY : GameEngine/MakeSound/MakeSound.o

# target to build an object file
GameEngine/MakeSound/MakeSound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/MakeSound/MakeSound.cpp.o
.PHONY : GameEngine/MakeSound/MakeSound.cpp.o

GameEngine/MakeSound/MakeSound.i: GameEngine/MakeSound/MakeSound.cpp.i

.PHONY : GameEngine/MakeSound/MakeSound.i

# target to preprocess a source file
GameEngine/MakeSound/MakeSound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/MakeSound/MakeSound.cpp.i
.PHONY : GameEngine/MakeSound/MakeSound.cpp.i

GameEngine/MakeSound/MakeSound.s: GameEngine/MakeSound/MakeSound.cpp.s

.PHONY : GameEngine/MakeSound/MakeSound.s

# target to generate assembly for a file
GameEngine/MakeSound/MakeSound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/MakeSound/MakeSound.cpp.s
.PHONY : GameEngine/MakeSound/MakeSound.cpp.s

GameEngine/MakeSound/sound.o: GameEngine/MakeSound/sound.cpp.o

.PHONY : GameEngine/MakeSound/sound.o

# target to build an object file
GameEngine/MakeSound/sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/MakeSound/sound.cpp.o
.PHONY : GameEngine/MakeSound/sound.cpp.o

GameEngine/MakeSound/sound.i: GameEngine/MakeSound/sound.cpp.i

.PHONY : GameEngine/MakeSound/sound.i

# target to preprocess a source file
GameEngine/MakeSound/sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/MakeSound/sound.cpp.i
.PHONY : GameEngine/MakeSound/sound.cpp.i

GameEngine/MakeSound/sound.s: GameEngine/MakeSound/sound.cpp.s

.PHONY : GameEngine/MakeSound/sound.s

# target to generate assembly for a file
GameEngine/MakeSound/sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/MakeSound/sound.cpp.s
.PHONY : GameEngine/MakeSound/sound.cpp.s

GameEngine/Window/window.o: GameEngine/Window/window.cpp.o

.PHONY : GameEngine/Window/window.o

# target to build an object file
GameEngine/Window/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Window/window.cpp.o
.PHONY : GameEngine/Window/window.cpp.o

GameEngine/Window/window.i: GameEngine/Window/window.cpp.i

.PHONY : GameEngine/Window/window.i

# target to preprocess a source file
GameEngine/Window/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Window/window.cpp.i
.PHONY : GameEngine/Window/window.cpp.i

GameEngine/Window/window.s: GameEngine/Window/window.cpp.s

.PHONY : GameEngine/Window/window.s

# target to generate assembly for a file
GameEngine/Window/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/GameEngine/Window/window.cpp.s
.PHONY : GameEngine/Window/window.cpp.s

src/Game/Game.o: src/Game/Game.cpp.o

.PHONY : src/Game/Game.o

# target to build an object file
src/Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Game.cpp.o
.PHONY : src/Game/Game.cpp.o

src/Game/Game.i: src/Game/Game.cpp.i

.PHONY : src/Game/Game.i

# target to preprocess a source file
src/Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Game.cpp.i
.PHONY : src/Game/Game.cpp.i

src/Game/Game.s: src/Game/Game.cpp.s

.PHONY : src/Game/Game.s

# target to generate assembly for a file
src/Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Game.cpp.s
.PHONY : src/Game/Game.cpp.s

src/Game/Game_assets_loader.o: src/Game/Game_assets_loader.cpp.o

.PHONY : src/Game/Game_assets_loader.o

# target to build an object file
src/Game/Game_assets_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Game_assets_loader.cpp.o
.PHONY : src/Game/Game_assets_loader.cpp.o

src/Game/Game_assets_loader.i: src/Game/Game_assets_loader.cpp.i

.PHONY : src/Game/Game_assets_loader.i

# target to preprocess a source file
src/Game/Game_assets_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Game_assets_loader.cpp.i
.PHONY : src/Game/Game_assets_loader.cpp.i

src/Game/Game_assets_loader.s: src/Game/Game_assets_loader.cpp.s

.PHONY : src/Game/Game_assets_loader.s

# target to generate assembly for a file
src/Game/Game_assets_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Game_assets_loader.cpp.s
.PHONY : src/Game/Game_assets_loader.cpp.s

src/Game/Player/Player.o: src/Game/Player/Player.cpp.o

.PHONY : src/Game/Player/Player.o

# target to build an object file
src/Game/Player/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/Player.cpp.o
.PHONY : src/Game/Player/Player.cpp.o

src/Game/Player/Player.i: src/Game/Player/Player.cpp.i

.PHONY : src/Game/Player/Player.i

# target to preprocess a source file
src/Game/Player/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/Player.cpp.i
.PHONY : src/Game/Player/Player.cpp.i

src/Game/Player/Player.s: src/Game/Player/Player.cpp.s

.PHONY : src/Game/Player/Player.s

# target to generate assembly for a file
src/Game/Player/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/Player.cpp.s
.PHONY : src/Game/Player/Player.cpp.s

src/Game/Player/ia_1.o: src/Game/Player/ia_1.cpp.o

.PHONY : src/Game/Player/ia_1.o

# target to build an object file
src/Game/Player/ia_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/ia_1.cpp.o
.PHONY : src/Game/Player/ia_1.cpp.o

src/Game/Player/ia_1.i: src/Game/Player/ia_1.cpp.i

.PHONY : src/Game/Player/ia_1.i

# target to preprocess a source file
src/Game/Player/ia_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/ia_1.cpp.i
.PHONY : src/Game/Player/ia_1.cpp.i

src/Game/Player/ia_1.s: src/Game/Player/ia_1.cpp.s

.PHONY : src/Game/Player/ia_1.s

# target to generate assembly for a file
src/Game/Player/ia_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/ia_1.cpp.s
.PHONY : src/Game/Player/ia_1.cpp.s

src/Game/Player/ia_2.o: src/Game/Player/ia_2.cpp.o

.PHONY : src/Game/Player/ia_2.o

# target to build an object file
src/Game/Player/ia_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/ia_2.cpp.o
.PHONY : src/Game/Player/ia_2.cpp.o

src/Game/Player/ia_2.i: src/Game/Player/ia_2.cpp.i

.PHONY : src/Game/Player/ia_2.i

# target to preprocess a source file
src/Game/Player/ia_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/ia_2.cpp.i
.PHONY : src/Game/Player/ia_2.cpp.i

src/Game/Player/ia_2.s: src/Game/Player/ia_2.cpp.s

.PHONY : src/Game/Player/ia_2.s

# target to generate assembly for a file
src/Game/Player/ia_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/Player/ia_2.cpp.s
.PHONY : src/Game/Player/ia_2.cpp.s

src/Game/core/bomb_collision.o: src/Game/core/bomb_collision.cpp.o

.PHONY : src/Game/core/bomb_collision.o

# target to build an object file
src/Game/core/bomb_collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bomb_collision.cpp.o
.PHONY : src/Game/core/bomb_collision.cpp.o

src/Game/core/bomb_collision.i: src/Game/core/bomb_collision.cpp.i

.PHONY : src/Game/core/bomb_collision.i

# target to preprocess a source file
src/Game/core/bomb_collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bomb_collision.cpp.i
.PHONY : src/Game/core/bomb_collision.cpp.i

src/Game/core/bomb_collision.s: src/Game/core/bomb_collision.cpp.s

.PHONY : src/Game/core/bomb_collision.s

# target to generate assembly for a file
src/Game/core/bomb_collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bomb_collision.cpp.s
.PHONY : src/Game/core/bomb_collision.cpp.s

src/Game/core/bombs.o: src/Game/core/bombs.cpp.o

.PHONY : src/Game/core/bombs.o

# target to build an object file
src/Game/core/bombs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bombs.cpp.o
.PHONY : src/Game/core/bombs.cpp.o

src/Game/core/bombs.i: src/Game/core/bombs.cpp.i

.PHONY : src/Game/core/bombs.i

# target to preprocess a source file
src/Game/core/bombs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bombs.cpp.i
.PHONY : src/Game/core/bombs.cpp.i

src/Game/core/bombs.s: src/Game/core/bombs.cpp.s

.PHONY : src/Game/core/bombs.s

# target to generate assembly for a file
src/Game/core/bombs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bombs.cpp.s
.PHONY : src/Game/core/bombs.cpp.s

src/Game/core/bonus.o: src/Game/core/bonus.cpp.o

.PHONY : src/Game/core/bonus.o

# target to build an object file
src/Game/core/bonus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bonus.cpp.o
.PHONY : src/Game/core/bonus.cpp.o

src/Game/core/bonus.i: src/Game/core/bonus.cpp.i

.PHONY : src/Game/core/bonus.i

# target to preprocess a source file
src/Game/core/bonus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bonus.cpp.i
.PHONY : src/Game/core/bonus.cpp.i

src/Game/core/bonus.s: src/Game/core/bonus.cpp.s

.PHONY : src/Game/core/bonus.s

# target to generate assembly for a file
src/Game/core/bonus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/bonus.cpp.s
.PHONY : src/Game/core/bonus.cpp.s

src/Game/core/death_time.o: src/Game/core/death_time.cpp.o

.PHONY : src/Game/core/death_time.o

# target to build an object file
src/Game/core/death_time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/death_time.cpp.o
.PHONY : src/Game/core/death_time.cpp.o

src/Game/core/death_time.i: src/Game/core/death_time.cpp.i

.PHONY : src/Game/core/death_time.i

# target to preprocess a source file
src/Game/core/death_time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/death_time.cpp.i
.PHONY : src/Game/core/death_time.cpp.i

src/Game/core/death_time.s: src/Game/core/death_time.cpp.s

.PHONY : src/Game/core/death_time.s

# target to generate assembly for a file
src/Game/core/death_time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/death_time.cpp.s
.PHONY : src/Game/core/death_time.cpp.s

src/Game/core/draw_map.o: src/Game/core/draw_map.cpp.o

.PHONY : src/Game/core/draw_map.o

# target to build an object file
src/Game/core/draw_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/draw_map.cpp.o
.PHONY : src/Game/core/draw_map.cpp.o

src/Game/core/draw_map.i: src/Game/core/draw_map.cpp.i

.PHONY : src/Game/core/draw_map.i

# target to preprocess a source file
src/Game/core/draw_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/draw_map.cpp.i
.PHONY : src/Game/core/draw_map.cpp.i

src/Game/core/draw_map.s: src/Game/core/draw_map.cpp.s

.PHONY : src/Game/core/draw_map.s

# target to generate assembly for a file
src/Game/core/draw_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/draw_map.cpp.s
.PHONY : src/Game/core/draw_map.cpp.s

src/Game/core/end.o: src/Game/core/end.cpp.o

.PHONY : src/Game/core/end.o

# target to build an object file
src/Game/core/end.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/end.cpp.o
.PHONY : src/Game/core/end.cpp.o

src/Game/core/end.i: src/Game/core/end.cpp.i

.PHONY : src/Game/core/end.i

# target to preprocess a source file
src/Game/core/end.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/end.cpp.i
.PHONY : src/Game/core/end.cpp.i

src/Game/core/end.s: src/Game/core/end.cpp.s

.PHONY : src/Game/core/end.s

# target to generate assembly for a file
src/Game/core/end.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/end.cpp.s
.PHONY : src/Game/core/end.cpp.s

src/Game/core/pause.o: src/Game/core/pause.cpp.o

.PHONY : src/Game/core/pause.o

# target to build an object file
src/Game/core/pause.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/pause.cpp.o
.PHONY : src/Game/core/pause.cpp.o

src/Game/core/pause.i: src/Game/core/pause.cpp.i

.PHONY : src/Game/core/pause.i

# target to preprocess a source file
src/Game/core/pause.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/pause.cpp.i
.PHONY : src/Game/core/pause.cpp.i

src/Game/core/pause.s: src/Game/core/pause.cpp.s

.PHONY : src/Game/core/pause.s

# target to generate assembly for a file
src/Game/core/pause.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Game/core/pause.cpp.s
.PHONY : src/Game/core/pause.cpp.s

src/Indie.o: src/Indie.cpp.o

.PHONY : src/Indie.o

# target to build an object file
src/Indie.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Indie.cpp.o
.PHONY : src/Indie.cpp.o

src/Indie.i: src/Indie.cpp.i

.PHONY : src/Indie.i

# target to preprocess a source file
src/Indie.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Indie.cpp.i
.PHONY : src/Indie.cpp.i

src/Indie.s: src/Indie.cpp.s

.PHONY : src/Indie.s

# target to generate assembly for a file
src/Indie.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Indie.cpp.s
.PHONY : src/Indie.cpp.s

src/Menu/Menu.o: src/Menu/Menu.cpp.o

.PHONY : src/Menu/Menu.o

# target to build an object file
src/Menu/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/Menu.cpp.o
.PHONY : src/Menu/Menu.cpp.o

src/Menu/Menu.i: src/Menu/Menu.cpp.i

.PHONY : src/Menu/Menu.i

# target to preprocess a source file
src/Menu/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/Menu.cpp.i
.PHONY : src/Menu/Menu.cpp.i

src/Menu/Menu.s: src/Menu/Menu.cpp.s

.PHONY : src/Menu/Menu.s

# target to generate assembly for a file
src/Menu/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/Menu.cpp.s
.PHONY : src/Menu/Menu.cpp.s

src/Menu/border/border.o: src/Menu/border/border.cpp.o

.PHONY : src/Menu/border/border.o

# target to build an object file
src/Menu/border/border.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/border/border.cpp.o
.PHONY : src/Menu/border/border.cpp.o

src/Menu/border/border.i: src/Menu/border/border.cpp.i

.PHONY : src/Menu/border/border.i

# target to preprocess a source file
src/Menu/border/border.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/border/border.cpp.i
.PHONY : src/Menu/border/border.cpp.i

src/Menu/border/border.s: src/Menu/border/border.cpp.s

.PHONY : src/Menu/border/border.s

# target to generate assembly for a file
src/Menu/border/border.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/border/border.cpp.s
.PHONY : src/Menu/border/border.cpp.s

src/Menu/chose_map/chose_map.o: src/Menu/chose_map/chose_map.cpp.o

.PHONY : src/Menu/chose_map/chose_map.o

# target to build an object file
src/Menu/chose_map/chose_map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_map/chose_map.cpp.o
.PHONY : src/Menu/chose_map/chose_map.cpp.o

src/Menu/chose_map/chose_map.i: src/Menu/chose_map/chose_map.cpp.i

.PHONY : src/Menu/chose_map/chose_map.i

# target to preprocess a source file
src/Menu/chose_map/chose_map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_map/chose_map.cpp.i
.PHONY : src/Menu/chose_map/chose_map.cpp.i

src/Menu/chose_map/chose_map.s: src/Menu/chose_map/chose_map.cpp.s

.PHONY : src/Menu/chose_map/chose_map.s

# target to generate assembly for a file
src/Menu/chose_map/chose_map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_map/chose_map.cpp.s
.PHONY : src/Menu/chose_map/chose_map.cpp.s

src/Menu/chose_map/map.o: src/Menu/chose_map/map.cpp.o

.PHONY : src/Menu/chose_map/map.o

# target to build an object file
src/Menu/chose_map/map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_map/map.cpp.o
.PHONY : src/Menu/chose_map/map.cpp.o

src/Menu/chose_map/map.i: src/Menu/chose_map/map.cpp.i

.PHONY : src/Menu/chose_map/map.i

# target to preprocess a source file
src/Menu/chose_map/map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_map/map.cpp.i
.PHONY : src/Menu/chose_map/map.cpp.i

src/Menu/chose_map/map.s: src/Menu/chose_map/map.cpp.s

.PHONY : src/Menu/chose_map/map.s

# target to generate assembly for a file
src/Menu/chose_map/map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_map/map.cpp.s
.PHONY : src/Menu/chose_map/map.cpp.s

src/Menu/chose_mode/chose_mode.o: src/Menu/chose_mode/chose_mode.cpp.o

.PHONY : src/Menu/chose_mode/chose_mode.o

# target to build an object file
src/Menu/chose_mode/chose_mode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_mode/chose_mode.cpp.o
.PHONY : src/Menu/chose_mode/chose_mode.cpp.o

src/Menu/chose_mode/chose_mode.i: src/Menu/chose_mode/chose_mode.cpp.i

.PHONY : src/Menu/chose_mode/chose_mode.i

# target to preprocess a source file
src/Menu/chose_mode/chose_mode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_mode/chose_mode.cpp.i
.PHONY : src/Menu/chose_mode/chose_mode.cpp.i

src/Menu/chose_mode/chose_mode.s: src/Menu/chose_mode/chose_mode.cpp.s

.PHONY : src/Menu/chose_mode/chose_mode.s

# target to generate assembly for a file
src/Menu/chose_mode/chose_mode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_mode/chose_mode.cpp.s
.PHONY : src/Menu/chose_mode/chose_mode.cpp.s

src/Menu/chose_mode/mode.o: src/Menu/chose_mode/mode.cpp.o

.PHONY : src/Menu/chose_mode/mode.o

# target to build an object file
src/Menu/chose_mode/mode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_mode/mode.cpp.o
.PHONY : src/Menu/chose_mode/mode.cpp.o

src/Menu/chose_mode/mode.i: src/Menu/chose_mode/mode.cpp.i

.PHONY : src/Menu/chose_mode/mode.i

# target to preprocess a source file
src/Menu/chose_mode/mode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_mode/mode.cpp.i
.PHONY : src/Menu/chose_mode/mode.cpp.i

src/Menu/chose_mode/mode.s: src/Menu/chose_mode/mode.cpp.s

.PHONY : src/Menu/chose_mode/mode.s

# target to generate assembly for a file
src/Menu/chose_mode/mode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/chose_mode/mode.cpp.s
.PHONY : src/Menu/chose_mode/mode.cpp.s

src/Menu/setting/setting.o: src/Menu/setting/setting.cpp.o

.PHONY : src/Menu/setting/setting.o

# target to build an object file
src/Menu/setting/setting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/setting.cpp.o
.PHONY : src/Menu/setting/setting.cpp.o

src/Menu/setting/setting.i: src/Menu/setting/setting.cpp.i

.PHONY : src/Menu/setting/setting.i

# target to preprocess a source file
src/Menu/setting/setting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/setting.cpp.i
.PHONY : src/Menu/setting/setting.cpp.i

src/Menu/setting/setting.s: src/Menu/setting/setting.cpp.s

.PHONY : src/Menu/setting/setting.s

# target to generate assembly for a file
src/Menu/setting/setting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/setting.cpp.s
.PHONY : src/Menu/setting/setting.cpp.s

src/Menu/setting/sound.o: src/Menu/setting/sound.cpp.o

.PHONY : src/Menu/setting/sound.o

# target to build an object file
src/Menu/setting/sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/sound.cpp.o
.PHONY : src/Menu/setting/sound.cpp.o

src/Menu/setting/sound.i: src/Menu/setting/sound.cpp.i

.PHONY : src/Menu/setting/sound.i

# target to preprocess a source file
src/Menu/setting/sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/sound.cpp.i
.PHONY : src/Menu/setting/sound.cpp.i

src/Menu/setting/sound.s: src/Menu/setting/sound.cpp.s

.PHONY : src/Menu/setting/sound.s

# target to generate assembly for a file
src/Menu/setting/sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/sound.cpp.s
.PHONY : src/Menu/setting/sound.cpp.s

src/Menu/setting/step.o: src/Menu/setting/step.cpp.o

.PHONY : src/Menu/setting/step.o

# target to build an object file
src/Menu/setting/step.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/step.cpp.o
.PHONY : src/Menu/setting/step.cpp.o

src/Menu/setting/step.i: src/Menu/setting/step.cpp.i

.PHONY : src/Menu/setting/step.i

# target to preprocess a source file
src/Menu/setting/step.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/step.cpp.i
.PHONY : src/Menu/setting/step.cpp.i

src/Menu/setting/step.s: src/Menu/setting/step.cpp.s

.PHONY : src/Menu/setting/step.s

# target to generate assembly for a file
src/Menu/setting/step.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/step.cpp.s
.PHONY : src/Menu/setting/step.cpp.s

src/Menu/setting/window_size.o: src/Menu/setting/window_size.cpp.o

.PHONY : src/Menu/setting/window_size.o

# target to build an object file
src/Menu/setting/window_size.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/window_size.cpp.o
.PHONY : src/Menu/setting/window_size.cpp.o

src/Menu/setting/window_size.i: src/Menu/setting/window_size.cpp.i

.PHONY : src/Menu/setting/window_size.i

# target to preprocess a source file
src/Menu/setting/window_size.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/window_size.cpp.i
.PHONY : src/Menu/setting/window_size.cpp.i

src/Menu/setting/window_size.s: src/Menu/setting/window_size.cpp.s

.PHONY : src/Menu/setting/window_size.s

# target to generate assembly for a file
src/Menu/setting/window_size.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/setting/window_size.cpp.s
.PHONY : src/Menu/setting/window_size.cpp.s

src/Menu/skin/skin.o: src/Menu/skin/skin.cpp.o

.PHONY : src/Menu/skin/skin.o

# target to build an object file
src/Menu/skin/skin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/skin/skin.cpp.o
.PHONY : src/Menu/skin/skin.cpp.o

src/Menu/skin/skin.i: src/Menu/skin/skin.cpp.i

.PHONY : src/Menu/skin/skin.i

# target to preprocess a source file
src/Menu/skin/skin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/skin/skin.cpp.i
.PHONY : src/Menu/skin/skin.cpp.i

src/Menu/skin/skin.s: src/Menu/skin/skin.cpp.s

.PHONY : src/Menu/skin/skin.s

# target to generate assembly for a file
src/Menu/skin/skin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/skin/skin.cpp.s
.PHONY : src/Menu/skin/skin.cpp.s

src/Menu/username/username.o: src/Menu/username/username.cpp.o

.PHONY : src/Menu/username/username.o

# target to build an object file
src/Menu/username/username.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/username/username.cpp.o
.PHONY : src/Menu/username/username.cpp.o

src/Menu/username/username.i: src/Menu/username/username.cpp.i

.PHONY : src/Menu/username/username.i

# target to preprocess a source file
src/Menu/username/username.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/username/username.cpp.i
.PHONY : src/Menu/username/username.cpp.i

src/Menu/username/username.s: src/Menu/username/username.cpp.s

.PHONY : src/Menu/username/username.s

# target to generate assembly for a file
src/Menu/username/username.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Menu/username/username.cpp.s
.PHONY : src/Menu/username/username.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/print_doc.o: src/print_doc.cpp.o

.PHONY : src/print_doc.o

# target to build an object file
src/print_doc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/print_doc.cpp.o
.PHONY : src/print_doc.cpp.o

src/print_doc.i: src/print_doc.cpp.i

.PHONY : src/print_doc.i

# target to preprocess a source file
src/print_doc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/print_doc.cpp.i
.PHONY : src/print_doc.cpp.i

src/print_doc.s: src/print_doc.cpp.s

.PHONY : src/print_doc.s

# target to generate assembly for a file
src/print_doc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/print_doc.cpp.s
.PHONY : src/print_doc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... GameEngine/Event/window_closed.o"
	@echo "... GameEngine/Event/window_closed.i"
	@echo "... GameEngine/Event/window_closed.s"
	@echo "... GameEngine/Keyboard/key_pressed.o"
	@echo "... GameEngine/Keyboard/key_pressed.i"
	@echo "... GameEngine/Keyboard/key_pressed.s"
	@echo "... GameEngine/MakeSound/MakeSound.o"
	@echo "... GameEngine/MakeSound/MakeSound.i"
	@echo "... GameEngine/MakeSound/MakeSound.s"
	@echo "... GameEngine/MakeSound/sound.o"
	@echo "... GameEngine/MakeSound/sound.i"
	@echo "... GameEngine/MakeSound/sound.s"
	@echo "... GameEngine/Window/window.o"
	@echo "... GameEngine/Window/window.i"
	@echo "... GameEngine/Window/window.s"
	@echo "... src/Game/Game.o"
	@echo "... src/Game/Game.i"
	@echo "... src/Game/Game.s"
	@echo "... src/Game/Game_assets_loader.o"
	@echo "... src/Game/Game_assets_loader.i"
	@echo "... src/Game/Game_assets_loader.s"
	@echo "... src/Game/Player/Player.o"
	@echo "... src/Game/Player/Player.i"
	@echo "... src/Game/Player/Player.s"
	@echo "... src/Game/Player/ia_1.o"
	@echo "... src/Game/Player/ia_1.i"
	@echo "... src/Game/Player/ia_1.s"
	@echo "... src/Game/Player/ia_2.o"
	@echo "... src/Game/Player/ia_2.i"
	@echo "... src/Game/Player/ia_2.s"
	@echo "... src/Game/core/bomb_collision.o"
	@echo "... src/Game/core/bomb_collision.i"
	@echo "... src/Game/core/bomb_collision.s"
	@echo "... src/Game/core/bombs.o"
	@echo "... src/Game/core/bombs.i"
	@echo "... src/Game/core/bombs.s"
	@echo "... src/Game/core/bonus.o"
	@echo "... src/Game/core/bonus.i"
	@echo "... src/Game/core/bonus.s"
	@echo "... src/Game/core/death_time.o"
	@echo "... src/Game/core/death_time.i"
	@echo "... src/Game/core/death_time.s"
	@echo "... src/Game/core/draw_map.o"
	@echo "... src/Game/core/draw_map.i"
	@echo "... src/Game/core/draw_map.s"
	@echo "... src/Game/core/end.o"
	@echo "... src/Game/core/end.i"
	@echo "... src/Game/core/end.s"
	@echo "... src/Game/core/pause.o"
	@echo "... src/Game/core/pause.i"
	@echo "... src/Game/core/pause.s"
	@echo "... src/Indie.o"
	@echo "... src/Indie.i"
	@echo "... src/Indie.s"
	@echo "... src/Menu/Menu.o"
	@echo "... src/Menu/Menu.i"
	@echo "... src/Menu/Menu.s"
	@echo "... src/Menu/border/border.o"
	@echo "... src/Menu/border/border.i"
	@echo "... src/Menu/border/border.s"
	@echo "... src/Menu/chose_map/chose_map.o"
	@echo "... src/Menu/chose_map/chose_map.i"
	@echo "... src/Menu/chose_map/chose_map.s"
	@echo "... src/Menu/chose_map/map.o"
	@echo "... src/Menu/chose_map/map.i"
	@echo "... src/Menu/chose_map/map.s"
	@echo "... src/Menu/chose_mode/chose_mode.o"
	@echo "... src/Menu/chose_mode/chose_mode.i"
	@echo "... src/Menu/chose_mode/chose_mode.s"
	@echo "... src/Menu/chose_mode/mode.o"
	@echo "... src/Menu/chose_mode/mode.i"
	@echo "... src/Menu/chose_mode/mode.s"
	@echo "... src/Menu/setting/setting.o"
	@echo "... src/Menu/setting/setting.i"
	@echo "... src/Menu/setting/setting.s"
	@echo "... src/Menu/setting/sound.o"
	@echo "... src/Menu/setting/sound.i"
	@echo "... src/Menu/setting/sound.s"
	@echo "... src/Menu/setting/step.o"
	@echo "... src/Menu/setting/step.i"
	@echo "... src/Menu/setting/step.s"
	@echo "... src/Menu/setting/window_size.o"
	@echo "... src/Menu/setting/window_size.i"
	@echo "... src/Menu/setting/window_size.s"
	@echo "... src/Menu/skin/skin.o"
	@echo "... src/Menu/skin/skin.i"
	@echo "... src/Menu/skin/skin.s"
	@echo "... src/Menu/username/username.o"
	@echo "... src/Menu/username/username.i"
	@echo "... src/Menu/username/username.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/print_doc.o"
	@echo "... src/print_doc.i"
	@echo "... src/print_doc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

